# Generated by Django 3.2.4 on 2021-06-09 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demoobjectmodel',
            name='just_string',
        ),
        migrations.AddField(
            model_name='demoobjectmodel',
            name='demo_entry',
            field=models.CharField(default=1, max_length=50, verbose_name='Добавить запись'),
            preserve_default=False,
        ),
    ]
